In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

if response code is 403

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
requests.get('URL here',headers=headers).text

In [5]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers).text

# this gives us the html code of the url

We use find_all when there is chance to get multiple answers

other wise use only find

In [7]:
soup=BeautifulSoup(webpage, 'html.parser')

In [11]:
soup.find_all('h1')[0].text

'\n\t\t\t\t\tTop Companies in\n\t\t\t\t \n\t\t\t\t\tINDIA\n\t\t\t\t\t'

In [12]:
len(soup.find_all('h2'))  # there are total 24 h2

24

In [14]:
for i in soup.find_all('h2'):
    print(i.text.strip())   # strip() will remove all the gaps bw data

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Jio
Axis Bank
Concentrix Corporation
Amazon
iEnergizer
Reliance Retail
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [15]:
for i in soup.find_all('p'):
    print(i.text.strip())

AmbitionBox
About Company
Discover best places to work
Compare & find best workplace
Bring your workplace to life
Highlight your company's perks
Read reviews for 6L+ companies
Rate your former or current company
Discover salaries for 6L+ companies
Calculate your take home salary
Check your market value
Help other jobseekers
Check your gratuity amount
Check how much of your HRA is tax-free
Check your salary hike
Read interviews for 40K+ companies
Contribute your interview questions
AmbitionBox Employee Choice Awards - 5th Edition
AmbitionBox Employee Choice Awards - 4th Edition
AmbitionBox Employee Choice Awards - 3rd Edition
Popular
AmbitionBox Award Winner'25
AmbitionBox Award Winner'25
AmbitionBox Award Winner'25
AmbitionBox Award Winner'25
AmbitionBox Award Winner'25
AmbitionBox Award Winner'25
AmbitionBox Award Winner'25
Side-by-side comparison to make informed career
										decisions
Trusted by over
									1.5 Crore
									job seekers to find their right fit company
Reviews
Salaries
Interviews
Users
About Company
Made with ❤️ in India. Trademarks belong to their respective owners. All
					rights reserved © 2026 Info Edge (India) Ltd.

In [25]:
len(soup.find_all('a', class_='review-count'))

0

In [26]:
company=soup.find_all('div', class_='companyCardWrapper__primaryInformation')
len(company)

20

In [78]:
name=[]
rating=[]
for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find_all('div', class_='rating_text rating_text--md')[0].text.strip())
d={'name':name, 'rating':rating}
df=pd.DataFrame(d)
df  # df of 1st page of info

                      name rating
0                      TCS    3.3
1                Accenture    3.7
2                    Wipro    3.6
3                Cognizant    3.6
4                Capgemini    3.7
5                HDFC Bank    3.8
6                  Infosys    3.5
7               ICICI Bank    4.0
8                  HCLTech    3.4
9            Tech Mahindra    3.4
10                 Genpact    3.6
11         Teleperformance    3.8
12                     Jio    4.4
13               Axis Bank    3.6
14  Concentrix Corporation    3.6
15                  Amazon    3.9
16              iEnergizer    4.6
17         Reliance Retail    3.9
18             LTIMindtree    3.6
19                     IBM    3.9

In [83]:
# loop for info of 1st 100 pages 

final=pd.DataFrame()
for j in range(1,100):
    url='https://www.ambitionbox.com/list-of-companies?page={}'.format(j)
    
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage=requests.get(url, headers=headers).text

    soup=BeautifulSoup(webpage, 'html.parser')

    company=soup.find_all('div', class_='companyCardWrapper__primaryInformation')

    name=[]
    rating=[]
    for i in company:
        name.append(i.find('h2').text.strip())
        rating.append(i.find_all('div', class_='rating_text rating_text--md')[0].text.strip())
        
    d={'name':name, 'rating':rating}
    df=pd.DataFrame(d)

    final = pd.concat([final, df], ignore_index=True)

In [84]:
final

               name rating
0               TCS    3.3
1         Accenture    3.7
2             Wipro    3.6
3         Cognizant    3.6
4         Capgemini    3.7
...             ...    ...
1975  Roop Polymers    4.0
1976  Ambit Finvest    3.9
1977   NMDC Limited    4.2
1978    LendingKart    3.5
1979        RadiSys    3.8

[1980 rows x 2 columns]